// <auto-generated />
using System;
using DigitalWellBeingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalWellBeingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DigitalWellBeingApp.Models.AppCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("AppCategoryMappings");
                });

            modelBuilder.Entity("DigitalWellBeingApp.Models.AppUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsages");
                });

            modelBuilder.Entity("DigitalWellBeingApp.Models.CategoryDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ratio")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TriggerHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SourceCategory", "TargetCategory")
                        .IsUnique();

                    b.ToTable("CategoryDebts");
                });
#pragma warning restore 612, 618
        }
    }
}
